### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by andreas-** [alexzaitsev/apk-dependency-graph#10]
Trying out several release apk i get this error

`at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:58)
    at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:516)
    at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:267)
    at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
    at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
    at brut.apktool.Main.cmdDecode(Main.java:163)
    at brut.apktool.Main.main(Main.java:81)`

no difference if i run sh run.sh ... or java -jar ...

**Comment by alexzaitsev** [comment]
Please submit this crash to `apktool` repository: https://github.com/iBotPeaches/Apktool

**Comment by gwen14123** [comment]
It's because you have a wrong framework-res.apk file :
me i have download framework-res.apk on this website : https://basketbuild.com/filedl/devs?dev=aniruddhc&dl=aniruddhc/framework-res.apk
Now I haven't issue.

**Comment by gwen14123** [comment]
No the framework-res that you have given are bad too :
Try framework-res and SystemUI of this website inside of this archeve 👍 
http://www.mediafire.com/file/a3gi2gjeyyio3qp/lollipop_systemUI_frame-res.zip
