### ISSUE TITLE
Keep getting "java.lang.IllegalArgumentException"

### ISSUE THREAD

**Issue by pgetsos** [alexzaitsev/apk-dependency-graph#21]
Hi, just tried it on 2 projects I have and I keep having the following error:

    Exception in thread "main" java.lang.IllegalArgumentException: character to be escaped is missing
        at java.util.regex.Matcher.appendReplacement(Unknown Source)
        at java.util.regex.Matcher.replaceAll(Unknown Source)
        at java.lang.String.replaceAll(Unknown Source)
        at code.SmaliAnalyzer.run(Unknown Source)
        at code.Main.main(Unknown Source)

I thought it was due to the Greek characters I have on my first project, but the second one doesn't contain any... :/

Thanks

**Comment by ProgFelipe** [comment]
Having same issue:
`Exception in thread "main" java.lang.IllegalArgumentException: character to be escaped is missing
        at java.util.regex.Matcher.appendReplacement(Matcher.java:809)
        at java.util.regex.Matcher.replaceAll(Matcher.java:955)
        at java.lang.String.replaceAll(String.java:2223)
        at code.SmaliAnalyzer.run(Unknown Source)
        at code.Main.main(Unknown Source)`

**Comment by turing-tech** [comment]
Same issue

**Comment by adisiji** [comment]
me too

**Comment by codingWang** [comment]
me too

**Comment by alexzaitsev** [comment]
should be fixed in https://github.com/alexzaitsev/apk-dependency-graph/releases/tag/0.1.1

**Comment by ProgFelipe** [comment]
Thanks worked for me!!

**Comment by pgetsos** [comment]
Works, thanks!
