### ISSUE TITLE
NullPointerException when decoding values */* XMLs ...

### ISSUE THREAD

**Issue by rockerhieu** [alexzaitsev/apk-dependency-graph#4]
```
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/orca_composer_top_divider.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-tvdpi-v4/common_plus_signin_btn_text_light_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/orca_composer_tab_dark.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-tvdpi-v4/common_google_signin_btn_icon_dark_pressed.9.png". Renaming it to *.png.
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.NullPointerException
        at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:58)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:516)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:267)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
        at brut.apktool.Main.cmdDecode(Main.java:163)
        at brut.apktool.Main.main(Main.java:81)
Please check your filter!
```

**Comment by alexzaitsev** [comment]
Hello @rockerhieu and thank you 
This bug belongs to the `apktool` library. Please submit it here: https://github.com/iBotPeaches/Apktool and close this issue. 
Thank you very much.
